# Site settings
title: Cole Ternes | Resume
description: A resume website showing off me, my skills, and my portfolio
url: "" # the base hostname & protocol for your site

# User settings
username: Cole Ternes
user_description: Hello, my name is Cole Ternes. I recently graduated from Chapman University, earning myself a B.S. in Computer Science and a B.A. in Economics. During this time, I have gained software engineering experience in several programming languages, become familiar with industry standard tools, and hardened my critical thinking skills. I also acquired a greater understanding of the economy, as well as a curiousity for how the design of new software may impact the business environment.
user_personality: On a more personal note, I am captivated with space exploration and feel a deep responsibility for the environment. For fun, I enjoy the company of good friends and listening to my favorite band, Electric Light Orchestra.
user_title: Software Engineer
email: ternes@chapman.edu
linkedin_username: cole-dev-ternes
github_username: coleternes

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
